apiVersion: v1
kind: Secret
metadata:
  name: todo-dev
type: Opaque
stringData:
  dbname: "postgres"
  user: "postgres"
  password: "Password1!"
  host: "todopsql" # name of the postgres service in k8s
  port: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: todopsql
spec:
  selector:
    app: todopsql
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pv-claim
  labels:
    app: todopsql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todopsql
spec:
  selector:
    matchLabels:
      app: todopsql
  template:
    metadata:
      labels:
        app: todopsql
    spec:
      containers:
      - name: todopsql
        image: todopsql:1.0
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: todo-dev
                key: password
        volumeMounts:
          - name: psql-persistent-storage
            mountPath: /var/lib/postgres
      volumes:
        - name: psql-persistent-storage
          persistentVolumeClaim:
            claimName: psql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: todoapi
spec:
  type: NodePort
  selector:
    app: todoapi
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi
spec:
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      containers:
      - name: todoapi
        imagePullPolicy: Never
        image: todoapi:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: PSQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: todo-dev
                key: dbname
          - name: PSQL_USER
            valueFrom:
              secretKeyRef:
                name: todo-dev
                key: user
          - name: PSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: todo-dev
                key: password
          - name: PSQL_HOST
            valueFrom:
              secretKeyRef:
                name: todo-dev
                key: host
          - name: PSQL_PORT
            valueFrom:
              secretKeyRef:
                name: todo-dev
                key: port
