apiVersion: v1
kind: Secret
metadata:
  name: todo-dev
type: Opaque
stringData:
  dbname: "postgres"
  user: "postgres"
  password: "Password1!"
  host: "todopsql" # name of the postgres service in k8s
  port: "5432"
